"""initial schema

Revision ID: a895ae03ec5c
Revises: 
Create Date: 2026-08-06 17:08:18.586381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a895ae03ec5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verticals',
    sa.Column('code', sa.String(), nullable=False, comment="'event-production' | ..."),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('organisations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_vertical_id', sa.UUID(), nullable=True, comment='Pre-fills new projects; a tenant is not restricted to one vertical (PRD §4.2.1)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_terms',
    sa.Column('category', sa.String(), nullable=False, comment="'deliverable_class' | 'milestone_type' | 'vendor_category' | 'commitment_act' | 'deviation_class' | 'venue_construct' | 'phase'"),
    sa.Column('code', sa.String(), nullable=False, comment='stable machine key, never renamed once referenced'),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_zh', sa.String(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ontology_terms.id'], ),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'code', 'vertical_id', 'organisation_id', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_ontology_terms_category'), 'ontology_terms', ['category'], unique=False)
    op.create_index(op.f('ix_ontology_terms_organisation_id'), 'ontology_terms', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_ontology_terms_vertical_id'), 'ontology_terms', ['vertical_id'], unique=False)
    op.create_table('parties',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('person', 'vendor_org', 'internal_staff', name='party_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_organisation_id'), 'parties', ['organisation_id'], unique=False)
    op.create_table('projects',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('event_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organisation_id'), 'projects', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_projects_vertical_id'), 'projects', ['vertical_id'], unique=False)
    op.create_table('budgets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False, comment='FK to users table, deferred to identity module; Finance/Producer role only'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_of', sa.UUID(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('length(currency) = 3', name='budget_currency_iso4217_length'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_of'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_project_id'), 'budgets', ['project_id'], unique=False)
    op.create_table('channel_identities',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.Enum('whatsapp', 'wechat', 'teams', 'outlook', 'sharepoint', name='channel_type'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False, comment='phone / WeChat ID / UPN / email'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('manually_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_type', 'external_id')
    )
    op.create_index(op.f('ix_channel_identities_party_id'), 'channel_identities', ['party_id'], unique=False)
    op.create_table('channels',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('whatsapp', 'wechat', 'teams', 'outlook', 'sharepoint', name='channel_type'), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True, comment='Group ID / mailbox / drive ID, per channel type'),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_project_id'), 'channels', ['project_id'], unique=False)
    op.create_table('milestones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type_term_id', sa.UUID(), nullable=False, comment="ontology_terms row, category='milestone_type'"),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=False, comment='FR-TWN-11: immovable node (doors open, venue hand-back)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['type_term_id'], ['ontology_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('class_term_id', sa.UUID(), nullable=False, comment="ontology_terms row, category='deliverable_class'"),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_term_id'], ['ontology_terms.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_milestone_id'), 'deliverables', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_deliverables_project_id'), 'deliverables', ['project_id'], unique=False)
    op.create_table('commitments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False, comment='who owes it'),
    sa.Column('counterparty_id', sa.UUID(), nullable=False, comment='whom it is owed to'),
    sa.Column('deliverable_id', sa.UUID(), nullable=True),
    sa.Column('act_type_id', sa.UUID(), nullable=False, comment="ontology_terms row, category='commitment_act' (universal core, PRD §4.2.1)"),
    sa.Column('state', sa.Enum('proposed', 'committed', 'at_risk', 'delivered', 'broken', 'renegotiated', 'withdrawn', name='commitment_state'), nullable=False),
    sa.Column('deliverable_en', sa.String(), nullable=False, comment='canonical EN noun phrase'),
    sa.Column('deliverable_original', sa.String(), nullable=True, comment='verbatim source language; equals deliverable_en if source is EN'),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_status', sa.Enum('unpaid', 'invoiced', 'paid', name='payment_status'), nullable=True, comment='FR-LED-13: Finance-role-set only, never inferred by the model'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_state', sa.Enum('auto', 'pending_verification', 'human_verified', 'human_corrected', name='verification_state'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True, comment='FK to users table, deferred to identity module'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('currency IS NULL OR length(currency) = 3', name='commitment_currency_iso4217_length'),
    sa.ForeignKeyConstraint(['act_type_id'], ['ontology_terms.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_project_id'), 'commitments', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('commitment_id', sa.UUID(), nullable=True),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True, comment='Points at the future Message/capture table — not modelled yet (Phase 1: Capture)'),
    sa.Column('channel', sa.Enum('whatsapp', 'wechat', 'teams', 'outlook', 'sharepoint', name='channel_type'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(), nullable=False, comment='bcp47'),
    sa.Column('original_text', sa.String(), nullable=False, comment='never overwritten'),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('media_ref', sa.String(), nullable=True, comment='signed, expiring URI'),
    sa.Column('transcript_confidence', sa.Float(), nullable=True, comment='voice only'),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(commitment_id IS NOT NULL)::int + (budget_id IS NOT NULL)::int = 1', name='evidence_exactly_one_subject'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_budget_id'), 'evidence', ['budget_id'], unique=False)
    op.create_index(op.f('ix_evidence_commitment_id'), 'evidence', ['commitment_id'], unique=False)
    # ### end Alembic commands ###

    # --- Evidence-linkage enforcement (FR-LED-03 / CLAUDE.md: "No commitment
    # without evidence... enforced at the DB layer, not trusted"). Not expressible
    # as a column-level CHECK, since it requires a *child table* (evidence) to have
    # at least one matching row — Postgres CHECK constraints cannot query other
    # tables. A deferred constraint trigger is the correct mechanism: it runs at
    # COMMIT, not per-statement, so a single transaction may insert a commitment
    # and its evidence row in either order.
    op.execute("""
        CREATE OR REPLACE FUNCTION check_commitment_has_evidence() RETURNS trigger AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM evidence WHERE commitment_id = NEW.id) THEN
            RAISE EXCEPTION 'commitment % has no evidence (FR-LED-03)', NEW.id;
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER commitment_requires_evidence
        AFTER INSERT OR UPDATE ON commitments
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_commitment_has_evidence();
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION check_budget_has_evidence() RETURNS trigger AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM evidence WHERE budget_id = NEW.id) THEN
            RAISE EXCEPTION 'budget % has no evidence (PRD §4.3)', NEW.id;
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER budget_requires_evidence
        AFTER INSERT OR UPDATE ON budgets
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_budget_has_evidence();
    """)

    # --- Row-level tenant isolation (CUE-Tech-Stack.md P1: RLS gives per-tenant
    # isolation in the database rather than the application). Demonstrated on
    # organisations, projects and commitments — extend the same pattern to
    # remaining tenant-owned tables as they're added; not done exhaustively here.
    # Scoped by the `app.current_org_id` session variable, set per-request by
    # RBAC middleware (see app/core/db.py). NULLIF(..., '') compared against a
    # column means an *unset* session variable denies all rows — fails closed.
    #
    # FORCE ROW LEVEL SECURITY matters even for a non-superuser owner, but by
    # itself is NOT sufficient: RLS does not apply to a superuser or a role
    # with BYPASSRLS at all, regardless of FORCE — and the bootstrap role this
    # migration runs as (`cue`) is both. The app connects at runtime as
    # `cue_app` instead (db/init/01-create-app-role.sql, app/core/config.py's
    # `database_url` vs `migration_database_url`), a genuinely unprivileged
    # role, which is what actually makes this policy real rather than inert.
    #
    # asyncpg prepares each execute() as a single statement, so every
    # semicolon-separated command below must be its own op.execute() call —
    # unlike psycopg2, it will not accept a multi-statement string.
    op.execute("ALTER TABLE organisations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE organisations FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON organisations
          USING (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
    """)
    op.execute("ALTER TABLE projects ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE projects FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON projects
          USING (organisation_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
    """)
    op.execute("ALTER TABLE commitments ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE commitments FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON commitments
          USING (project_id IN (
            SELECT id FROM projects
            WHERE organisation_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
          ));
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON commitments;")
    op.execute("ALTER TABLE commitments DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON projects;")
    op.execute("ALTER TABLE projects DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON organisations;")
    op.execute("ALTER TABLE organisations DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP TRIGGER IF EXISTS budget_requires_evidence ON budgets;")
    op.execute("DROP FUNCTION IF EXISTS check_budget_has_evidence();")
    op.execute("DROP TRIGGER IF EXISTS commitment_requires_evidence ON commitments;")
    op.execute("DROP FUNCTION IF EXISTS check_commitment_has_evidence();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_commitment_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_budget_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_commitments_project_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_deliverables_project_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_milestone_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_channels_project_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_channel_identities_party_id'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index(op.f('ix_budgets_project_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_projects_vertical_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organisation_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_parties_organisation_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_ontology_terms_vertical_id'), table_name='ontology_terms')
    op.drop_index(op.f('ix_ontology_terms_organisation_id'), table_name='ontology_terms')
    op.drop_index(op.f('ix_ontology_terms_category'), table_name='ontology_terms')
    op.drop_table('ontology_terms')
    op.drop_table('organisations')
    op.drop_table('verticals')
    # ### end Alembic commands ###
