"""add commitment verification_reasons

`verification_state` says a human has to look at a row; it does not say what
to look at. Every route into `pending_verification` collapses into that one
state deliberately — one queue a PM checks, not five — which leaves a triage
problem the moment the queue is more than a handful of rows: a price waiting
for confirmation and a possible hallucination arrive the same colour.

Hand-written rather than autogenerated. `alembic revision --autogenerate`
produced a 35KB diff of pre-existing column-comment drift plus an unrelated
index drop, none of it this change; applying that would have made a
one-column migration into an unreviewable one.

Revision ID: f3157fe92ddc
Revises: b2d94f7c1a08
Create Date: 2026-08-20 13:51:11.082657
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f3157fe92ddc"
down_revision: Union[str, Sequence[str], None] = "b2d94f7c1a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "commitments",
        sa.Column(
            "verification_reasons",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            # Existing rows predate the column and cannot have their reasons
            # reconstructed — verification_state was the only thing recorded.
            # An empty array is honest about that; backfilling a guessed
            # reason would be worse than saying nothing.
            server_default=sa.text("'{}'::varchar[]"),
            comment=(
                "Why this row is in the review queue, set at extraction time. "
                "verification_state says a human must look; this says what to "
                "look at."
            ),
        ),
    )


def downgrade() -> None:
    op.drop_column("commitments", "verification_reasons")
